service: stupid
provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: ap-northeast-2

functions:
  express:
    handler: handler.express
    environment:
      CHANNEL_SECRET: ${env:CHANNEL_SECRET}
      CHANNEL_ACCESS_TOKEN: ${env:CHANNEL_ACCESS_TOKEN}
      DB_HOST: ${env:DB_HOST}
      DB_PASSWORD: ${env:DB_PASSWORD}
      DB_ID: ${env:DB_ID}
      DB_NAME: ${env:DB_NAME}
    events:
      - http:
          path: webhook
          method: post

